### ISSUE TITLE
Any way to get this as a docker image?

### ISSUE THREAD

**Issue by raykai** [bravecollective/bravecollective-intel#8]
would be nice to have this in a docker image. would be a lot simpler for ppl to use.

Even more, if we could get all of the brave apps in a docker image and ready to go, now that would be brave :P

**Comment by tehraven** [comment]
This whole project is just simple PHP and a java applet. Almost any nginx + php7 image you find would be compatible.

Make a branch with a Dockerfile at root and I'm sure you can get it working.
